# /etc/writeonce/services/iwd.service.toml
#
# Wireless daemon. WPA/WPA2/WPA3 association + built-in DHCP for wifi.
# Replaces wpa_supplicant.

[unit]
description = "iNet Wireless Daemon"
after       = ["dbus.service"]
requires    = ["dbus.service"]

[service]
type        = "simple"
exec-start  = "/usr/libexec/iwd"
restart     = "on-failure"
restart-sec = "5s"
user        = "root"
group       = "root"
slice       = "system.slice"

[install]
wanted-by   = ["multi-user.target"]
